spring:
  application:
    name: notification-service

  kafka:
    bootstrap-servers: localhost:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: waghmodenagesh18@gmail.com
    password: your_app_password_here
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

notification:
  topic:
    name: order-notification

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
